{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "release-validation-framework.gatewayName" . }}
  labels:
    {{- include "release-validation-framework.labels" . | nindent 4 }}
  {{- if or .Values.gateway.annotations .Values.certmanager.enabled }}
  annotations:
    {{- with .Values.gateway.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.certmanager.enabled }}
    {{- if or .Values.certmanager.issuer.create (not (empty .Values.certmanager.issuerName)) }}
    cert-manager.io/issuer: {{ include "release-validation-framework.issuerName" . | quote }}
    {{- else if .Values.certmanager.clusterIssuerName }}
    cert-manager.io/cluster-issuer: {{ .Values.certmanager.clusterIssuerName | quote }}
    {{- end }}
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
    {{- end }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  {{- $infraAnnotations := or .Values.gateway.infrastructureAnnotations (and .Values.gateway.infrastructure .Values.gateway.infrastructure.annotations) }}
  {{- with $infraAnnotations }}
  infrastructure:
    annotations:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  listeners:
    {{- if or .Values.certmanager.enabled .Values.gateway.listeners.http.enabled }}
    - name: {{ .Values.gateway.listeners.http.name }}
      protocol: {{ .Values.gateway.listeners.http.protocol }}
      port: {{ .Values.gateway.listeners.http.port }}
      allowedRoutes:
        {{- toYaml .Values.gateway.listeners.http.allowedRoutes | nindent 8 }}
    {{- end }}
    {{- if .Values.gateway.listeners.https.enabled }}
    - name: {{ .Values.gateway.listeners.https.name }}
      port: {{ .Values.gateway.listeners.https.port }}
      hostname: {{ .Values.gateway.listeners.https.hostname }}
      allowedRoutes:
        {{- toYaml .Values.gateway.listeners.https.allowedRoutes | nindent 8 }}
      {{- if .Values.gateway.tls.enabled }}
      protocol: HTTPS
      tls:
        mode: {{ .Values.gateway.tls.mode }}
        certificateRefs:
          - kind: Secret
            name: {{ .Values.gateway.tls.certificateSecret }}
      {{- else }}
      protocol: HTTP
      {{- end }}
    {{- end }}
{{- end }}
